import { Itinerary, Trip } from "@/types";

function uid() {
  return Math.random().toString(36).slice(2) + Date.now().toString(36);
}

export const MOCK_ITINERARY: Itinerary = {
  id: uid(),
  destination: "Ooty, Tamil Nadu",
  overview:
    "Ooty (Udhagamandalam), nestled in the Nilgiri Hills, is a stunning hill station known for its tea gardens, colonial architecture, and cool climate. This 3-day itinerary covers the best of the Queen of Hill Stations.",
  num_days: 3,
  num_travelers: 2,
  total_estimated_cost: 9200,
  budget: 10000,
  currency: "INR",
  budget_remaining: 800,
  tags: ["hill station", "nature", "heritage", "tea gardens"],
  created_at: new Date().toISOString(),
  days: [
    {
      day: 1,
      date: "Day 1",
      title: "Arrival & Scenic Highlights",
      theme: "Explore iconic viewpoints and botanical wonders",
      day_total_cost: 2800,
      activities: [
        {
          id: uid(),
          name: "Ooty Lake",
          description: "Serene artificial lake — enjoy a boat ride with stunning Nilgiri views.",
          time: "10:00 AM",
          duration_hours: 1.5,
          estimated_cost: 200,
          currency: "INR",
          is_estimate: true,
          category: "sightseeing",
          location: "Ooty Lake Rd",
        },
        {
          id: uid(),
          name: "Government Botanical Gardens",
          description: "150-year-old gardens spread over 22 hectares with 650+ plant species.",
          time: "12:00 PM",
          duration_hours: 2,
          estimated_cost: 150,
          currency: "INR",
          is_estimate: false,
          category: "sightseeing",
          location: "Charring Cross",
        },
        {
          id: uid(),
          name: "Lunch at Sidewalk Café",
          description: "Popular local restaurant — try the Nilgiri tea and local cuisine.",
          time: "2:00 PM",
          duration_hours: 1,
          estimated_cost: 600,
          currency: "INR",
          is_estimate: true,
          category: "food",
        },
        {
          id: uid(),
          name: "Doddabetta Peak",
          description: "Highest peak in the Nilgiris at 2,637m — panoramic views across Tamil Nadu.",
          time: "4:00 PM",
          duration_hours: 2,
          estimated_cost: 20,
          currency: "INR",
          is_estimate: false,
          category: "adventure",
          location: "Doddabetta, 10km from Ooty",
        },
      ],
      accommodation: {
        name: "Sterling Ooty Elk Hill",
        type: "Resort",
        estimated_cost_per_night: 1800,
        currency: "INR",
        is_estimate: true,
        rating: 4.2,
        location: "Elk Hill, Ooty",
      },
    },
    {
      day: 2,
      date: "Day 2",
      title: "Tea Gardens & Heritage Railway",
      theme: "Tea culture, colonial history & scenic train ride",
      day_total_cost: 3100,
      activities: [
        {
          id: uid(),
          name: "Nilgiri Mountain Railway",
          description: "UNESCO World Heritage rack railway — the memorable 'toy train' experience.",
          time: "9:00 AM",
          duration_hours: 3,
          estimated_cost: 400,
          currency: "INR",
          is_estimate: false,
          category: "transport",
          location: "Ooty Railway Station",
        },
        {
          id: uid(),
          name: "Tea Factory Visit",
          description: "Tour a working tea factory, learn the processing steps and taste freshly brewed Nilgiri tea.",
          time: "1:00 PM",
          duration_hours: 1.5,
          estimated_cost: 150,
          currency: "INR",
          is_estimate: true,
          category: "culture",
          location: "Ketti Valley",
        },
        {
          id: uid(),
          name: "Lunch at Hotel Adyar Ananda Bhavan",
          description: "Famous South Indian vegetarian thali.",
          time: "2:30 PM",
          duration_hours: 1,
          estimated_cost: 500,
          currency: "INR",
          is_estimate: true,
          category: "food",
        },
        {
          id: uid(),
          name: "Rose Garden",
          description: "Asia's largest rose garden with 20,000+ varieties.",
          time: "4:00 PM",
          duration_hours: 1.5,
          estimated_cost: 100,
          currency: "INR",
          is_estimate: false,
          category: "sightseeing",
        },
      ],
      accommodation: {
        name: "Sterling Ooty Elk Hill",
        type: "Resort",
        estimated_cost_per_night: 1800,
        currency: "INR",
        is_estimate: true,
        rating: 4.2,
        location: "Elk Hill, Ooty",
      },
    },
    {
      day: 3,
      date: "Day 3",
      title: "Waterfalls & Departure",
      theme: "Nature walks and farewell treats",
      day_total_cost: 1500,
      activities: [
        {
          id: uid(),
          name: "Pykara Falls & Lake",
          description: "Beautiful waterfalls 21km from Ooty — great for nature photography.",
          time: "9:00 AM",
          duration_hours: 3,
          estimated_cost: 300,
          currency: "INR",
          is_estimate: true,
          category: "sightseeing",
          location: "Pykara, 21km from Ooty",
        },
        {
          id: uid(),
          name: "Mudumalai Wildlife Sanctuary (optional)",
          description: "Spot elephants, deer, and leopards on a jeep safari.",
          time: "12:00 PM",
          duration_hours: 2,
          estimated_cost: 500,
          currency: "INR",
          is_estimate: true,
          category: "adventure",
          location: "40km from Ooty",
        },
        {
          id: uid(),
          name: "Shopping at Ooty Market",
          description: "Pick up homemade chocolates, eucalyptus oil, and fresh Nilgiri tea.",
          time: "3:00 PM",
          duration_hours: 1.5,
          estimated_cost: 500,
          currency: "INR",
          is_estimate: true,
          category: "shopping",
          location: "Municipal Market, Ooty",
        },
      ],
    },
  ],
  transportation: [
    {
      mode: "Bus / Car",
      from: "Chennai",
      to: "Ooty",
      estimated_cost: 1200,
      currency: "INR",
      duration: "11–13 hours",
      is_estimate: true,
      notes: "TNSTC buses available; private car ~₹3,500",
    },
    {
      mode: "Auto / Local Taxi",
      from: "Ooty",
      to: "Local sightseeing",
      estimated_cost: 600,
      currency: "INR",
      duration: "Per day",
      is_estimate: true,
    },
  ],
  research_sources: [
    {
      title: "Tamil Nadu Tourism — Ooty",
      url: "https://www.tamilnadutourism.tn.gov.in/ooty",
      description: "Official tourism page with permits and timings",
    },
    {
      title: "Nilgiri Mountain Railway — Indian Railways",
      url: "https://www.irctc.co.in",
      description: "Book toy train tickets online",
    },
    {
      title: "TripAdvisor — Ooty Hotels",
      url: "https://www.tripadvisor.in/Hotels-g297682-Ooty_Udhagamandalam_Nilgiris_District_Tamil_Nadu-Hotels.html",
      description: "Hotel reviews and prices",
    },
  ],
};

export const MOCK_TRIPS: Trip[] = [
  {
    id: uid(),
    title: "3 Days in Ooty",
    destination: "Ooty, Tamil Nadu",
    start_date: "2024-12-20",
    end_date: "2024-12-23",
    created_at: new Date(Date.now() - 86400000).toISOString(),
    session_id: "session-001",
    itinerary: MOCK_ITINERARY,
  },
  {
    id: uid(),
    title: "Budget Goa Trip",
    destination: "Goa",
    start_date: "2025-01-10",
    end_date: "2025-01-15",
    created_at: new Date(Date.now() - 172800000).toISOString(),
    session_id: "session-002",
  },
  {
    id: uid(),
    title: "Weekend Coorg Getaway",
    destination: "Coorg, Karnataka",
    start_date: "2025-02-05",
    end_date: "2025-02-07",
    created_at: new Date(Date.now() - 259200000).toISOString(),
    session_id: "session-003",
  },
];

export const MOCK_WELCOME_MESSAGES: string[] = [
  "✈️ Hello! I'm your **SmartTrip AI Travel Agent**. I can help you plan unforgettable trips personalized to your budget, style, and travel group.\n\nTell me where you'd like to go (e.g., *Munnar, Goa, Rajasthan*), or pick one of the suggestions below!",
];
